<table align="left" width=100%>
    <tr>
        <td width="20%">
            <img src="faculty.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                  <b> Assignment Questions </b>
                </font>
            </div>
        </td>
    </tr>
</table>

Total Marks:  30 Marks


### About the data set (Movie_Reviews)

The dataset contains Movie reviews. The aim of this assignment is to classsify the review texts into two categories. 

Attribute information: 
 
Dataset has two columns:
Column1: Review Text
Column2: Two Classes. Positive and negative.

## Table of Content

1. **[Import Libraries](#lib)**
2. **[Load the Data  (5 Marks)](#prep)**
    - 2.1 - **[Read the Data   (1 Mark)](#read)**
    - 2.2 - **[Dispay the first ten rows (1 Mark) ](#dtype)**
    - 2.3 - **[Display the information about the data (1 Mark)](#drop)**
    - 2.4 - **[Encode the sentiment column values as 1 or 0 (2 Marks)](#dummy)**
3.  **[Data preprocessing  (7 Marks)](#prep)**
    - 3.1 - **[Remove special characters and html tags (2 Marks)](#read)**
    - 3.2 - **[Convert reviews into lowercase (1 Mark)](#dtype)**
    - 3.3 - **[Removal of stop words (2 Marks)](#drop)**
    - 3.4 - **[Apply stemming (2 Marks)](#dummy)**
4.**[Convert review text into feature vector and classification (18 Marks)](#prep)**
    - 4.1 - **[create BOW model (2 Marks)](#cut_off)**
    - 4.2 - **[Training data and Test data -split  (1 Mark)](#dtype)**
    - 4.3 - **[Define the Classification model (any one like NB, SVM or Random forest) train the model  (3 Marks) ](#drop)**
    - 4.4 - **[Classification metrics analysis (2 Marks)](#dummy)**
    - 4.5 - **[predict the class for your own review (2 Marks)](#dummy)**

    - 4.6 - **[create feature vector using tf-idf  (2 Marks)](#cut_off)**
    - 4.7 - **[Define the Classification model (any one like NB, SVM or Random forest) train the model (2 Marks)](#drop)**
    - 4.8 - **[Classification metrics analysis (2 Marks)](#dummy)**
    - 4.9 - **[predict the class for your own review (2 Marks) ](#dummy)**

        

<a id="lib"></a>
# 1. Import Libraries

**Let us import the required libraries.**

In [1]:
import numpy as np
import pandas as pd

In [2]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [25]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [3]:
import pickle
import tensorflow as tf
from nltk.corpus import stopwords
import string

2. Load the Data

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


2.1 Read the data

In [5]:
data=pd.read_excel('Movie_reviews.xlsx')

2.2 Dispay the first ten rows

In [6]:
data.head(10)

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive
5  Probably my all-time favorite movie, a story o...  positive
6  I sure would like to see a resurrection of a u...  positive
7  This show was an amazing, fresh & innovative i...  negative
8  Encouraged by the positive comments about this...  negative
9  If you like original gut wrenching laughter yo...  positive

2.3 Display the information about the data

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB


2.4   Encode the sentiment column values as 1 or 0

In [8]:
y = pd.get_dummies(data['sentiment'])
y = y.iloc[:,1].values

In [9]:
y

array([1, 1, 1, ..., 0, 0, 0], dtype=uint8)

3.  Data preprocessing

3.1 Remove special characters and html tags

In [17]:
#cleaning the text
from bs4 import BeautifulSoup
import re

def strip(data):
    soup = BeautifulSoup(data, "html.parser")
    data = re.sub('\[[^]]*\]', '', soup.get_text())
    pattern=r"[^a-zA-z0-9\s,']"
    data=re.sub(pattern,'',data)
    return data

data['review']=data['review'].apply(strip)

3.2 - Convert reviews into lowercase

In [19]:
def removing_noise(text):
    text = re.sub('[^a-zA-Z0-9\s]', ' ', text)
    text = text.lower()

    return text


3.3 - Removal of stop words

In [20]:
def remove_stopwords(text):
    text= ' '.join([word for word in text.split() if word not in stopwords.words('english')])
    return text

3.4 - Apply stemming

In [21]:
def simple_stemmer(text):
    ps = PorterStemmer()
    text= ' '.join([ps.stem(word) for word in text.split()])
    return text

In [22]:
def main_func(text):
    text = removing_noise(text)
    text = remove_stopwords(text)
    text = simple_stemmer(text)
    return text

In [28]:
text = data['review'].apply(main_func)

4.  Convert review text into feature vector and classification

4.1 - create BOW model 

In [29]:


from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=2500)
x = cv.fit_transform(data['review']).toarray()

4.2 - Training data and Test data -split

In [30]:
# Train Test Split

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 0)

4.3 - Define the Classification model (any one like NB, SVM or Random forest) train the model

In [31]:
from sklearn.naive_bayes import MultinomialNB
multiNB_model = MultinomialNB().fit(X_train, y_train)

4.4  Classification metrics analysis and plot the confusion matrix

In [32]:
y_pred = multiNB_model.predict(X_test)
from sklearn.metrics import confusion_matrix,classification_report
print(classification_report(y_pred,y_test))
print(confusion_matrix(y_test,y_pred))


              precision    recall  f1-score   support

           0       0.83      0.81      0.82      5153
           1       0.81      0.83      0.82      4847

    accuracy                           0.82     10000
   macro avg       0.82      0.82      0.82     10000
weighted avg       0.82      0.82      0.82     10000

[[4189  846]
 [ 964 4001]]


4.5 - predict the class for your own review

In [33]:
user = input("Enter your movie review")

data = cv.transform([user]).toarray()
output = multiNB_model.predict(data)
print(output)

Enter your movie reviewOne of the best of all time
[1]


4.6 - create feature vector using tf-idf

In [44]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(max_features=2500)
x=tfidf.fit_transform(text).toarray()

4.7 Define the Classification model (any one like NB, SVM or Random forest) train the model

In [45]:
# Train Test Split

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 0)

In [46]:
from sklearn.naive_bayes import MultinomialNB
multiNB_model = MultinomialNB().fit(X_train, y_train)

4.8 - Classification metrics analysis

In [47]:
y_pred = multiNB_model.predict(X_test)
from sklearn.metrics import confusion_matrix,classification_report
print(classification_report(y_pred,y_test))


              precision    recall  f1-score   support

           0       0.83      0.85      0.84      4937
           1       0.85      0.84      0.84      5063

    accuracy                           0.84     10000
   macro avg       0.84      0.84      0.84     10000
weighted avg       0.84      0.84      0.84     10000



In [48]:
print(confusion_matrix(y_test,y_pred))

[[4204  831]
 [ 733 4232]]


4.9 - predict the class for your own review

In [49]:
user = input("Enter your movie review")

data = cv.transform([user]).toarray()
output = multiNB_model.predict(data)
print(output)

Enter your movie reviewfantabulous
[1]
